import csv
import sys

# Define your input and output files
infile = 'data/p_chinensis_rotated.backbone'
outfile = 'results/P_chinensis_structural_blocks.csv'

# Short names for CSV headers to keep downstream scripts happy
genomes = ['VN1', 'CH1', 'CH2', 'Shorea', 'Thebroma']

print(f"Reading {infile}...")

try:
    with open(infile, 'r') as f_in, open(outfile, 'w', newline='') as f_out:
        writer = csv.writer(f_out)
        
        # Create a clean header row for your CSV
        header = ['Block_ID']
        for g in genomes:
            header.extend([f'{g}_Start', f'{g}_End', f'{g}_Strand'])
        writer.writerow(header)
        
        block_id = 1
        for line in f_in:
            line = line.strip()
            # Skip the header lines generated by Mauve
            if line.startswith('seq') or line.startswith('#') or not line:
                continue
                
            cols = line.split()
            row = [f"LCB_{block_id}"]
            
            # Mauve backbone files use 2 columns per genome (left_coord right_coord)
            for i in range(len(genomes)):
                idx = i * 2
                if idx >= len(cols):
                    break 
                
                val1 = int(cols[idx])
                val2 = int(cols[idx+1])
                
                # If both are 0, this block is missing in this specific genome
                if val1 == 0 and val2 == 0:
                    row.extend(['-', '-', '-'])
                else:
                    # Inversions are marked by negative coordinates in Mauve
                    strand = '-' if val1 < 0 else '+'
                    start = abs(val1)
                    end = abs(val2)
                    row.extend([start, end, strand])
                    
            writer.writerow(row)
            block_id += 1

    print(f"Success! Extracted {block_id - 1} homologous blocks.")
    print(f"Data saved to {outfile}")

except FileNotFoundError:
    print(f"Error: Could not find {infile}. Make sure you are in the correct directory.")